name: Build mosaic project
on:
  push:
    branches:
      - main
      - sparkr
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.8.10 ]
        spark: [ 3.2.1 ]
        R: [ 4.1.2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Test and build the scala JAR
        run: mvn -q clean install -DskipTests
      - name: Copy Scala artifacts to GH Actions run
        run: |
          mkdir staging
          cp target/mosaic*.jar staging
      #- name: Configure python interpreter
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: ${{ matrix.python }}
      #- name: Install python dependencies
      #  run: |
      #    cd python
      #    pip install build wheel pyspark==${{ matrix.spark }}
      #    pip install .
      #- name: Test and build python package
      #  run: |
      #    cd python 
      #    python -m unittest
      #    python -m build
      #- name: Copy python artifacts to GH Actions run
      #  run: cp python/dist/*.whl staging
      - name: Setup R build environment
        run: |
          sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev pkg-config
          mkdir -p /usr/local/lib/R/site-library
          sudo chown -R $USER: /usr/local/lib/R/site-library
      - name: Build R package
        run: |
          cd R/SparkR
          Rscript --vanilla build-r-package.R
          Rscript --vanilla sparkrMosaic/tests/not_devtools_tests.R
      - name: Copy R artifacts to GH Actions run
        run: cp R/SparkR/*.tar.gz staging
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: staging/*
